const Constants = {
  DRAGONFLOWER_CUTOFF_DATE: "2019-02-07",
  MAX_DRAGONFLOWERS_DEFAULT: 5,
  MAX_DRAGONFLOWERS_SPECIAL: 10,
  MAX_HERO_MERIT: 6000,
  MAX_LEVEL: 40,
  MAX_MERGES: 10,
  MAX_RARITY: 5,
  MAX_SKILL_POINTS: 9999,
};

export default Constants;
